config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"

  get "/recipes", to: "recipes#index", as: :recipes
  get "/recipe/:id", to: "recipes#show", as: :recipe
  get "/recipes/new", to: "recipes#new", as: :new_recipe
  post "/recipes/new", to: "recipes#create", as: false

  devise_for :users

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "bg_welcome2.jpg"
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Paperclip::Glue
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all.reverse
	end

	def show
		@recipe = Recipe.find params[:id]
	end

	def new
		@new_recipe = Recipe.new
	end

	def create
		@new_recipe = Recipe.create(params_recipe)
		@new_recipe.save
		if @new_recipe.save
			flash[:notice] = "Receita adicionada"
			redirect_to recipe_path(@new_recipe.id)
		else
			flash[:notice] = "Ops, ouve algum erro."
			render :new
		end

	end

	private
	def params_recipe
		params.require(:recipe).permit(:title, :description, :ingredients, :directions, :picture)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	if current_user
  		redirect_to recipes_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav
	    if current_user
	      render "layouts/nav_with_user"
	    else
	      render "layouts/nav_without_user"
		end
	end
	
end

app/views/layouts/_nav_with_user.html.erb
<p class="navbar-text navbar-right">
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' if current_user %>
</p>

<p class="navbar-text navbar-right">
  <%= link_to "Nova receita", new_recipe_path %>
</p>

<p class="navbar-text navbar-right">
  <%= notice %> <%= alert %> <%= current_user.email if current_user %>
</p>

app/views/layouts/_nav_without_user.html.erb
<p class="navbar-text navbar-right">
  <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link' unless current_user %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receita</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
</head>
<body ng-app="">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= image_tag "java.png", class: "Brand" %>
      </a>
    </div>

    <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Inicio", root_path unless current_user %></li>
        <li class="active"><%= link_to "Receitas", recipes_path if current_user %></li>
        <li><%= link_to "Receitas", recipes_path unless current_user %></li>
    </ul>

    <%= nav %>

  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<h1>Receitas</h1>

<div class="recipes-container">
</div>

<div class="recipes">

	<% @recipes.each do |recipe| %>
		<div class="recipe">
		<%= image_tag "bg_welcome2.jpg", id: "recipe-picture" %>
			<h1><%= link_to "#{recipe.title}", recipe_path(recipe.id) %></h1>
			<p>
				<%= recipe.description.first(150) %>
			</p>
		</div>
	<% end %>



		

</div>

app/views/recipes/new.html.erb
<div class="recipes-container">
</div>

<h1>Nova receita</h1>

<%= form_for @new_recipe, url: new_recipe_path do |recipe| %>

	<%= recipe.label :picture, "Envie uma foto" %>
	<%= recipe.file_field :picture %>

	<%= recipe.label :title, "Titulo" %><br>
	<%= recipe.text_field :title %><br>

	<%= recipe.label :description, "Descrisao" %><br>
	<%= recipe.text_area :description %><br>

	<%= recipe.label :ingredients, "Ingredientes" %>
	<small>utilize (virgula) para separar os ingredientes.</small><br>
	<%= recipe.text_area :ingredients%><br><br>

	<%= recipe.label :directions, "Modo de preparo" %><br>
	<%= recipe.text_area :directions, :'ng-model'=> "directions" %><br>

	<small>Exibiçao do Modo de preparo (verifique para ficar legivel)</small>
	<pre id="ingredients-exemple" ng-bind="directions"></pre>

	<%= recipe.submit "Cozinhar!" %>
<% end %>

app/views/recipes/show.html.erb
<div class="recipes-container">
</div>

<div class="recipe-bg">
</div>

<h1><%= @recipe.title %></h1>

<%= image_tag @recipe.picture.url, id: "recipe-picture", class: "recipe-picture" %>

<p id="recipe-description">
<%= @recipe.description %>
</p >

<br>

<div class="recipe-instructions">

	<ul>
		<li id="recipe-steps" onclick="show_ingredients();">INGREDIENTES</li>
		<li id="recipe-steps" onclick="show_preparation();">MODO DE PREPARO</li>
	</ul>

	<div class="recipe-ingredients" id="recipe-ingredients">
		<ul>	
			<% @recipe.ingredients.split(",").each do |recipe| %>
				<li id="recipe-ingredient"><%= recipe %></li>
			<% end %>
		</ul>	
	</div>

	<div class="recipe-preparation" id="recipe-preparation" >
		<pre>
<%= @recipe.directions %>
		</pre>
	</div>	

</div>

app/views/welcome/index.html.erb
<div class="welcome-container">

  <nav class="welcome-nav" id="welcome">
    <ul>
      <li><%= link_to "LOGIN", new_user_session_path %></li>
      <li><%= link_to "CADASTRO", new_user_registration_path %></li>
      <li>Receitas</li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
    </ul>
  </nav>

  <h1>Tudo Cozinha</h1>
  <p>sua coleção de sabores</p>

  <a href="#welcome-recipe">
    <%= image_tag "down_arrow.png", class: "welcome-arrow" %>
  </a>

</div>

<div class="welcome-recipe" id="welcome-recipe">

  <p>+ de 8000 receitas</p>

  <div class="welcome-show-recipes">
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome2.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
    <%= image_tag "bg_welcome.jpg", id: "welcome-recipe-list", class: "col-xs-1 col-md-1" %>
  </div>

</div>

<div class="welcome-actions row" id="welcome-actions">
  
  <div class="action col-xs-12 col-md-6" id="welcome-new-user" >
    <p>Crie sua conta e compartilhe deliciosas receitas</p>

    <input type="button" value="Cadastra-se" class="btn btn-primary">

  </div>

  <div class="action col-xs-12 col-md-6" id="welcome-new-recipe">
    <p>Faça já sua coleção de receitas, é facil</p>

    <input type="button" value="Entrar" class="btn btn-primary">

  </div>

</div>